export interface ArchiveSituation {
  id: string;
  pageNum: number;
  chapterTitle: string;
  date: string;
  location: string;
  country: string;
  category: '4x4' | 'rencontres' | 'volcans' | 'transports' | 'rituels' | 'nature';
  categoryLabel: string;
  photoUrl: string;
  photoCaption: string;
  cameraInfo: string;
  excerpt: string;
  quote: string;
  stats: {
    distanceKm: number;
    iconicSite: string;
  };
}

export const ARCHIVE_SITUATIONS: ArchiveSituation[] = [
  // --- 1. FRANCE (DÉPART & PRÉPARATIFS) ---
  {
    id: "sit-1",
    pageNum: 4,
    chapterTitle: "Les vaccins et l'épaule opérée de Patrice",
    date: "12 Février 2025",
    location: "Rennes",
    country: "France",
    category: "transports",
    categoryLabel: "✈️ Préparatifs & Défis",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 4 : Préparatifs médicaux et rééducation d'épaule avant le grand départ",
    cameraInfo: "Cliché d'archive Manuscrit p. 4 • Rennes",
    excerpt: "« Malgré une opération de l'épaule récente et une rééducation intensive chez le kiné, sans compter une vilaine grippe attrapée trois semaines avant le vol, l'envie de partir est plus forte que tout. Mam vérifie dix fois la trousse à pharmacie et les boîtes de Doliprane pour le mal de dos. »",
    quote: "« À 69 ans, les douleurs s'effacent dès que la passion du voyage prend le dessus. »",
    stats: { distanceKm: 0, iconicSite: "Cabinet Médical de Rennes" }
  },
  {
    id: "sit-2",
    pageNum: 7,
    chapterTitle: "Le Grand Départ à la Gare de Rennes (Jour J)",
    date: "16 Mars 2025",
    location: "Rennes",
    country: "France",
    category: "transports",
    categoryLabel: "✈️ Départ & Logistique",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 7 : Presque toute la famille à la gare de Rennes pour le Jour J",
    cameraInfo: "Cliché d'archive Manuscrit p. 7 • Rennes",
    excerpt: "« Presque toute la famille (il manque Raphael) nous accompagne à la gare y compris le dernier de nos petits fils de 4 ans en fauteuil roulant pour nous dire au revoir. Nous pouvons dire qu’il s’agit du moment émotion de la journée car notre fille extrêmement sensible a qq larmes avant même notre descente sur le quai de la gare. Il est normalement interdit aux non voyageurs mais un agent très compréhensif devant la tristesse de notre fille et nos lourds bagages, accepte de les faire entrer par la passerelle d’accès au quai afin de nous accompagner et nous aider. »",
    quote: "« Le premier pas d'un long voyage demande toujours un peu de bravoure et beaucoup de valises. »",
    stats: { distanceKm: 350, iconicSite: "Gare de Rennes & TGV" }
  },
  {
    id: "sit-3",
    pageNum: 8,
    chapterTitle: "Enregistrement de la montagne de valises à CDG",
    date: "16 Mars 2025",
    location: "Aéroport Paris Roissy CDG",
    country: "France",
    category: "transports",
    categoryLabel: "✈️ Logistique & Valises",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 8 : Pesée fatidique des bagages au Terminal 2E",
    cameraInfo: "Cliché d'archive Manuscrit p. 8 • Roissy CDG",
    excerpt: "« Arrivée à Roissy après notre trajet en TGV. La pesée des bagages au comptoir est un moment de suspense absolu. Mam surveille le cadran numérique comme l'aiguille d'une bombe ! Heureusement, nos efforts d'optimisation sont récompensés : 19.8 kg pour la première valise. On souffle enfin. »",
    quote: "« L'art du voyage réside dans le contrôle méticuleux du poids de son bagage en soute. »",
    stats: { distanceKm: 380, iconicSite: "Roissy CDG Terminal 2E" }
  },
  {
    id: "sit-4",
    pageNum: 8,
    chapterTitle: "Premier vol long-courrier vers l'Asie (Cathay Pacific)",
    date: "17 Mars 2025",
    location: "Vol CDG - Hong Kong",
    country: "France",
    category: "transports",
    categoryLabel: "✈️ Vol & Espace",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 8 : L'A350 de Cathay Pacific prêt à fendre les cieux",
    cameraInfo: "Cliché d'archive Manuscrit p. 8 • En Vol",
    excerpt: "« Embarquement immédiat à bord de l'Airbus A350. On s'installe confortablement. Patrice ajuste ses écouteurs pour écouter de la musique bretonne tandis que Mam scrute l'écran de vol indiquant 11 heures de trajet vers l'Extrême-Orient. C'est le vrai coup d'envoi. »",
    quote: "« Quand l'avion quitte la piste de Roissy, 69 ans de routine s'envolent dans les nuages. »",
    stats: { distanceKm: 9600, iconicSite: "Espace Aérien International" }
  },

  // --- 2. HONG KONG & CHINE (ESCALES) ---
  {
    id: "sit-5",
    pageNum: 9,
    chapterTitle: "Se perdre dans la Baie de Hong Kong & Victoria Peak",
    date: "18 Mars 2025",
    location: "Hong Kong",
    country: "Hong Kong",
    category: "rencontres",
    categoryLabel: "🤝 Rencontres & Escale",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 9 : Baie de HongKong vue du Peak Victoria (Pic Victoria)",
    cameraInfo: "Cliché d'archive Manuscrit p. 9 • Hong Kong",
    excerpt: "« Hgkg est une RAS chinoise (Région Administrative Spéciale) qui compte 7.5 millions d’habitants sur une surface 10 x grande comme Paris... Nous voilà partis mais manifestement pas dans la bonne direction et la, commencent les échanges de mots doux entre Mam et moi. Nous arrivons à nous perdre après avoir fait au moins 3 ou 4 km en tournant en rond... »",
    quote: "« Se perdre ensemble à 69 ans, c'est encore la meilleure manière de se retrouver. »",
    stats: { distanceKm: 9600, iconicSite: "Victoria Peak & Wan Chai" }
  },
  {
    id: "sit-6",
    pageNum: 11,
    chapterTitle: "Le marché nocturne de Temple Street à Kowloon",
    date: "19 Mars 2025",
    location: "Kowloon",
    country: "Hong Kong",
    category: "rituels",
    categoryLabel: "🍷 Saveurs & Nuit Asian",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 11 : Échoppes illuminées du night market de Temple Street",
    cameraInfo: "Cliché d'archive Manuscrit p. 11 • Kowloon",
    excerpt: "« Plongée nocturne au milieu des vapeurs de dim sum et des néons rouges du marché de Temple Street. Mam hésite devant des brochettes mystérieuses, mais nous finissons par déguster des gambas sautées au wok tout à fait succulentes. Un régal pour les papilles ! »",
    quote: "« L'exotisme se mesure à l'audace de goûter ce dont on ne peut prononcer le nom. »",
    stats: { distanceKm: 15, iconicSite: "Temple Street Night Market" }
  },
  {
    id: "sit-7",
    pageNum: 14,
    chapterTitle: "Le Feuilleton du passeport à l'aéroport de Haikou",
    date: "20 Mars 2025",
    location: "Haikou",
    country: "Chine",
    category: "transports",
    categoryLabel: "✈️ Transports & Péripéties",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 14 : Haikou Meilan International Airport (Chine)",
    cameraInfo: "Cliché d'archive Manuscrit p. 14 • Haikou",
    excerpt: "« 23H 15 enregistrement debute sans souci pile a l’heure indiquée et nous sommes dans la file d’attente pendant 30 mn environ puis arrive notre tour... Cette erreur emanne en fait de la Prefecture d’Ille et Vilaine qui a écrit un point au lieu d’un tiret a mon prenom jean-baptiste . Cette erreur a pour consequense que les services de l’immigration chinoise et neo zelandaise me baptisent de 4 prenoms et non de 3 . »",
    quote: "« Un simple point de frappe administrative peut déclencher un incident diplomatique en Asie ! »",
    stats: { distanceKm: 1400, iconicSite: "Haikou Meilan International Airport" }
  },

  // --- 3. NOUVELLE-ZÉLANDE (ÎLE DU NORD) ---
  {
    id: "sit-8",
    pageNum: 16,
    chapterTitle: "La Malédiction du pneu éclaté en 4x4 à Auckland",
    date: "21 Mars 2025",
    location: "Auckland",
    country: "Nouvelle-Zélande",
    category: "4x4",
    categoryLabel: "🤠 Péripéties & 4x4",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 16 : Baie d'Auckland — Ca commence mal au pays des kiwis",
    cameraInfo: "Cliché d'archive Manuscrit p. 16 • Auckland",
    excerpt: "« J’avais garé le 4X4 devant l’hotel en stationnement minute mais ne pouvais pas le laisser a cet endroit pour la nuit... Est-ce l’ennervement ou la fatigue du « jet stream » car il est déjà tres tard, mais en me garant au meme endroit j’éclate le pneu gauche sur le trottoir. Je suis furax contre moi meme et dois remonter expliquer tt ca a Mam qui ne manquera surement pas de s’exprimer. »",
    quote: "« Ca commence mal au pays des kiwis, mais un bon verre de Villa Maria répare tout. »",
    stats: { distanceKm: 9300, iconicSite: "Auckland Harbour & Waitemata" }
  },
  {
    id: "sit-9",
    pageNum: 19,
    chapterTitle: "Les arbres géants Kauri de la forêt de Waipoua",
    date: "22 Mars 2025",
    location: "Waipoua Forest",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Forêt & Géants",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 19 : Tane Mahuta, le Dieu de la Forêt vieux de 2000 ans",
    cameraInfo: "Cliché d'archive Manuscrit p. 19 • Waipoua",
    excerpt: "« Éblouissement absolu devant Tane Mahuta, le Seigneur de la Forêt. Cet arbre Kauri majestueux possède un tronc de près de 14 mètres de circonférence. Mam se sent toute petite au pied de ce colosse végétal qui poussait déjà à l'époque de l'Empire Romain ! »",
    quote: "« Le temps s'incline devant les géants de la nature néo-zélandaise. »",
    stats: { distanceKm: 210, iconicSite: "Tane Mahuta Kauri Tree" }
  },
  {
    id: "sit-10",
    pageNum: 23,
    chapterTitle: "Paihia & La croisière vers Hole in the Rock",
    date: "24 Mars 2025",
    location: "Paihia (Bay of Islands)",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Océan & Falaises",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 23 : Le catamaran approchant le fameux trou dans le rocher",
    cameraInfo: "Cliché d'archive Manuscrit p. 23 • Paihia",
    excerpt: "« Embarquement matinal à Paihia sur un catamaran puissant. La mer secoue un peu, mais le spectacle des 144 îles de la baie est féerique. On s'approche de la roche percée où les vagues s'engouffrent avec un rugissement impressionnant. »",
    quote: "« La baie des îles offre l'un des plus beaux décors marins de notre planète. »",
    stats: { distanceKm: 60, iconicSite: "Bay of Islands Marine Park" }
  },
  {
    id: "sit-11",
    pageNum: 28,
    chapterTitle: "Fabuleuse Valse des Dauphins à Paihia",
    date: "25 Mars 2025",
    location: "Paihia (Bay of Islands)",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Faune & Nature",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 28 : Fabuleuse valse des dauphins au large de Paihia",
    cameraInfo: "Cliché d'archive Manuscrit p. 28 • Paihia",
    excerpt: "« Puis lorsque des centaines de dauphins nous accompagnent vers le « Hole on the Rocks » ( trou du rocher en francais), Ils executent une danse aussi fascinante qu’émouvante en passant et repassant a droite a gauche devant derriere et sous le bateau comme pour nous dire qu’ils aiment jouer avec les remous provoqués par les turbines. C’est genial je descends me mettre a la proue du bateau. »",
    quote: "« Quand les dauphins escortent votre bateau, vous comprenez la magie de ce monde. »",
    stats: { distanceKm: 240, iconicSite: "Hole in the Rock & Bay of Islands" }
  },
  {
    id: "sit-12",
    pageNum: 31,
    chapterTitle: "Cape Reinga et l'affrontement des deux océans",
    date: "26 Mars 2025",
    location: "Cape Reinga",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Cap Sacré & Océans",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 31 : Le Phare de Cape Reinga et le choc des courants",
    cameraInfo: "Cliché d'archive Manuscrit p. 31 • Cape Reinga",
    excerpt: "« À la pointe nord extrême de la Nouvelle-Zélande, la Mer de Tasman rencontre l'Océan Pacifique dans un choc de vagues vrombissant. Les Maoris considèrent cet endroit comme le point de départ des âmes vers le royaume spirituel. Un moment chargé en frissons. »",
    quote: "« Là où deux océans se disputent l'horizon, le voyageur trouve le véritable apaisement. »",
    stats: { distanceKm: 210, iconicSite: "Cape Reinga Lighthouse" }
  },
  {
    id: "sit-13",
    pageNum: 34,
    chapterTitle: "Descente en luge sur les dunes géantes de Te Paki",
    date: "26 Mars 2025",
    location: "Te Paki Sand Dunes",
    country: "Nouvelle-Zélande",
    category: "rituels",
    categoryLabel: "🍷 Sensations & Dunes",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 34 : Patrice prêt à dévaler les dômes de sable doré",
    cameraInfo: "Cliché d'archive Manuscrit p. 34 • Te Paki",
    excerpt: "« Des montagnes de sable blond à perte de vue. Je ne peux pas résister : j'attrape une planche de bodyboard et me voilà parti à plat ventre du haut d'une digne de 80 mètres ! Mam pousse des cris effrayés mais s'amuse comme une gamine en me voyant arriver en bas la bouche pleine de sable ! »",
    quote: "« À 69 ans, dévaler une dune sur une planche ravive instantanément l'âme de ses 10 ans. »",
    stats: { distanceKm: 20, iconicSite: "Te Paki Giant Sand Dunes" }
  },
  {
    id: "sit-14",
    pageNum: 37,
    chapterTitle: "Les geysers fumants et fumerolles de Rotorua",
    date: "27 Mars 2025",
    location: "Rotorua (Te Puia)",
    country: "Nouvelle-Zélande",
    category: "volcans",
    categoryLabel: "🌋 Geysers & Soufre",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 37 : Le geyser Pohutu propulsant son eau bouillante à 30m",
    cameraInfo: "Cliché d'archive Manuscrit p. 37 • Rotorua",
    excerpt: "« Dès l'arrivée à Rotorua, l'odeur d'œuf pourri du soufre nous saisit au nez ! Le spectacle du geyser Pohutu jaillissant avec force toutes les 20 minutes au-dessus des roches volcaniques est tout simplement phénoménal. La Terre respire sous nos pieds. »",
    quote: "« Rotorua nous rappelle que notre planète est un organisme vivant et bouillonant. »",
    stats: { distanceKm: 380, iconicSite: "Geyser Pohutu Te Puia" }
  },
  {
    id: "sit-15",
    pageNum: 41,
    chapterTitle: "La Rencontre de Stephen & Ruth à Reporoa",
    date: "28 Mars 2025",
    location: "Reporoa",
    country: "Nouvelle-Zélande",
    category: "rencontres",
    categoryLabel: "🤝 Rencontres & Hospitalité",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 43 : 1ere tournée : 170 vaches descendent pour la traite du soir",
    cameraInfo: "Cliché d'archive Manuscrit p. 41-43 • Reporoa",
    excerpt: "« Nous arrivons donc chez eux en 25 mn et nous sommes merveilleusement accueillis dans leur belle petite maison avec une tasse de café et un gateau a la banane. Il est a noter car «tout ce qui est rare est a noter» (ah!ah!ah!), que meme Mam qui ne mange jamais de banane trouvera ce gateau excellent et en prendra 2x... Au moment de partir ils nous proposent d’assister à la traite d’un 1 er groupe de 170 betes. »",
    quote: "« Deux agriculteurs bretons au milieu du lait néo-zélandais : la vraie richesse du voyage. »",
    stats: { distanceKm: 400, iconicSite: "Ferme Laitière de Reporoa" }
  },
  {
    id: "sit-16",
    pageNum: 43,
    chapterTitle: "Assister à la traite des 170 vaches néo-zélandaises",
    date: "28 Mars 2025",
    location: "Reporoa",
    country: "Nouvelle-Zélande",
    category: "rencontres",
    categoryLabel: "🤝 Métier & Étable",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 43 : Le roto de traite géant en pleine action",
    cameraInfo: "Cliché d'archive Manuscrit p. 43 • Reporoa",
    excerpt: "« En tant qu'ancien professionnel de l'agriculture, observer ce carrousel de traite automatisé pour des centaines de vaches est fascinant. Stephen nous explique la gestion des pâturages et de l'herbe en Nouvelle-Zélande. Un échange entre passionnés de la terre. »",
    quote: "« Le langage des éleveurs et des passionnés de terre est universel au bout du monde. »",
    stats: { distanceKm: 0, iconicSite: "Étable Rotative de Reporoa" }
  },
  {
    id: "sit-17",
    pageNum: 45,
    chapterTitle: "Le gâteau à la banane d'exception de Ruth",
    date: "28 Mars 2025",
    location: "Reporoa",
    country: "Nouvelle-Zélande",
    category: "rituels",
    categoryLabel: "🍷 Gourmandise & Surprise",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 45 : Dégustation conviviale de banana cake dans le salon de Ruth",
    cameraInfo: "Cliché d'archive Manuscrit p. 45 • Reporoa",
    excerpt: "« Miracle gastronomique ! Mam, qui voue une haine féroce à la banane depuis son enfance, goûte du bout des dents au gâteau moelleux préparé par Ruth... et en reprend une deuxième part en souriant ! Un exploit historique qu'il fallait absolument consigner dans ce carnet. »",
    quote: "« Quand la politesse bretonne triomphe des phobies culinaires d'une vie ! »",
    stats: { distanceKm: 0, iconicSite: "Maison de Stephen & Ruth" }
  },
  {
    id: "sit-18",
    pageNum: 48,
    chapterTitle: "Le Lac Taupo et les spectaculaires chutes d'Huka Falls",
    date: "29 Mars 2025",
    location: "Lake Taupo",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Chutes & Eaux Turquoise",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 48 : L'eau bouillonnante et turquoise des Huka Falls",
    cameraInfo: "Cliché d'archive Manuscrit p. 48 • Taupo",
    excerpt: "« Plus de 220 000 litres d'eau par seconde se ruent dans un étroit goulet rocheux. La couleur bleu cyan de l'eau est irréelle. Nous restons scotchés sur la passerelle, enveloppés par la brume d'eau et le bruit fracassant du fleuve Waikato. »",
    quote: "« La puissance brute des chutes Huka Falls vous donne une leçon d'humilité. »",
    stats: { distanceKm: 90, iconicSite: "Huka Falls & Lake Taupo" }
  },
  {
    id: "sit-19",
    pageNum: 51,
    chapterTitle: "Randonnée sur les terres volcaniques du Mont Tongariro",
    date: "29 Mars 2025",
    location: "Tongariro National Park",
    country: "Nouvelle-Zélande",
    category: "volcans",
    categoryLabel: "🌋 Montagnes & Cratères",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 51 : Paysage lunaire du Mordor et lacs d'émeraude",
    cameraInfo: "Cliché d'archive Manuscrit p. 51 • Tongariro",
    excerpt: "« Marche au milieu d'un décor lunaire d'un autre monde, qui a servi de cadre aux films du Seigneur des Anneaux. L'air est vif, les roches noires volcaniques contrastent avec les lacs d'émeraude. Une traversée mémorable. »",
    quote: "« Marcher dans le Mordor à 69 ans sans se fouler la cheville : mission accomplie ! »",
    stats: { distanceKm: 120, iconicSite: "Emerald Lakes Tongariro" }
  },
  {
    id: "sit-20",
    pageNum: 55,
    chapterTitle: "Wellington la Venteuse & Le Musée Te Papa",
    date: "30 Mars 2025",
    location: "Wellington",
    country: "Nouvelle-Zélande",
    category: "rituels",
    categoryLabel: "🍷 Rituels & Culture",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 55 : Musée Te Papa (art & culture et traditions maori)",
    cameraInfo: "Cliché d'archive Manuscrit p. 55 • Wellington",
    excerpt: "« A noter que Wellington est la capitale de la NZ depuis 1875. Elle compte un peu plus de 200000 habitants et se situe au point le plus meridional de l’ile du Nord dans le detroit du capitaine james Cook qui a decouvert l’ile en 1769 . Sa position geographique en fait une ville tres venteuse qui lui donne dailleurs son surnom de «Windy Wellington» traduit en francais par «Wellington la venteuse». »",
    quote: "« La réputation de la capitale culturelle maorie n'est vraiment pas surfaite. »",
    stats: { distanceKm: 320, iconicSite: "Musée Te Papa & Port de Wellington" }
  },
  {
    id: "sit-21",
    pageNum: 58,
    chapterTitle: "Embarquement sur le ferry Interislander vers le Sud",
    date: "31 Mars 2025",
    location: "Détroit de Cook",
    country: "Nouvelle-Zélande",
    category: "transports",
    categoryLabel: "✈️ Traversée & Bateau",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 58 : Le grand ferry fendant les eaux agitées du Détroit de Cook",
    cameraInfo: "Cliché d'archive Manuscrit p. 58 • Interislander",
    excerpt: "« On monte à bord du ferry géant avec notre 4x4. La traversée du Détroit de Cook dure un peu plus de 3 heures. Le vent souffle fort sur le pont extérieur, mais le panorama lors de l'entrée dans les Marlborough Sounds est à couper le souffle. »",
    quote: "« Passer de l'Île du Nord à l'Île du Sud, c'est changer d'hémisphère poétique. »",
    stats: { distanceKm: 90, iconicSite: "Cook Strait & Interislander Ferry" }
  },
  {
    id: "sit-22",
    pageNum: 61,
    chapterTitle: "Arrivée magique dans les fjords de Picton",
    date: "31 Mars 2025",
    location: "Picton (Marlborough)",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Fjords & Sérénité",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 61 : Baies paisibles et collines verdoyantes de Picton",
    cameraInfo: "Cliché d'archive Manuscrit p. 61 • Picton",
    excerpt: "« Débarquement à Picton au soleil couchant. La lumière dorée caresse les pentes boisées qui plongent dans des eaux calmes comme un miroir. On prend la route sinueuse vers le vignoble de Marlborough avec une joie immense. »",
    quote: "« Picton est le port paisible qui vous ouvre les bras de l'Île du Sud. »",
    stats: { distanceKm: 35, iconicSite: "Picton Harbour Marlborough" }
  },

  // --- 4. NOUVELLE-ZÉLANDE (ÎLE DU SUD) ---
  {
    id: "sit-23",
    pageNum: 64,
    chapterTitle: "Chez Daniel Lebrun & Pique-nique à la Robinson",
    date: "1er Avril 2025",
    location: "Blenheim & Kaikoura",
    country: "Nouvelle-Zélande",
    category: "rituels",
    categoryLabel: "🍷 Rituels & Dégustations",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 65 : Petit arrêt surprise après Seldon sur la route de Kaikoura",
    cameraInfo: "Cliché d'archive Manuscrit p. 64-65 • Blenheim",
    excerpt: "« Le cas de Daniel Lebrun fondateur de N°1 Familly estate est pourtant particulier car apres ses etudes d’œnologie il souhaite s’emanciper et part en NZ tres jeune... On s’arrete sur la route a l’improviste sur un chemin de terre... On trouve un arbre en guise de fauteuil et de grosses pierres pour faire une table et apres une bonne promenade les pieds dans l'eau, on picnic a la Robinson Crusoé sans couverts avec ce luxe d’un bon verre de blanc raffraichit dans l'eau de mer. »",
    quote: "« Refroidir son vin blanc dans l'Océan Pacifique à 69 ans : la vraie définition du luxe. »",
    stats: { distanceKm: 130, iconicSite: "N°1 Family Estate Marlborough" }
  },
  {
    id: "sit-24",
    pageNum: 65,
    chapterTitle: "Pique-nique improvisé les pieds dans l'Océan à Kaikoura",
    date: "1er Avril 2025",
    location: "Kaikoura Coast",
    country: "Nouvelle-Zélande",
    category: "rituels",
    categoryLabel: "🍷 Pique-Nique & Liberté",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 65 : Notre table en pierre improvisée face aux vagues",
    cameraInfo: "Cliché d'archive Manuscrit p. 65 • Kaikoura",
    excerpt: "« Un morceau de pain frais, du fromage de chèvre local, des tomates bien mûres et une bouteille de méthode traditionnelle rafraîchie directement entre deux rochers battus par les vagues. Le bonheur tient dans la simplicité d'un arrêt imprévu au bord de la côte. »",
    quote: "« Pas besoin de nappes ni d'argenterie quand l'Océan vous sert de décor. »",
    stats: { distanceKm: 0, iconicSite: "Côte Sauvage de Kaikoura" }
  },
  {
    id: "sit-25",
    pageNum: 68,
    chapterTitle: "Observation des otaries à fourrure sur les rochers",
    date: "2 Avril 2025",
    location: "Point Kean (Kaikoura)",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Faune & Otaries",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 68 : Une famille d'otaries faisant la sieste au soleil",
    cameraInfo: "Cliché d'archive Manuscrit p. 68 • Point Kean",
    excerpt: "« À quelques mètres seulement de notre chemin, des dizaines d'otaries dorment paisiblement sur les dalles de récif. Les bébés jouent dans les mares d'eau résiduelles. Mam prend une photo rapprochée en retenant son souffle pour ne pas les réveiller. »",
    quote: "« Partager le rivage avec les animaux sauvages en toute quiétude. »",
    stats: { distanceKm: 15, iconicSite: "Point Kean Seal Colony" }
  },
  {
    id: "sit-26",
    pageNum: 72,
    chapterTitle: "Christchurch et sa cathédrale en carton",
    date: "3 Avril 2025",
    location: "Christchurch",
    country: "Nouvelle-Zélande",
    category: "rencontres",
    categoryLabel: "🤝 Architecture & Espoir",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 72 : La Cardboard Cathedral conçue par Shigeru Ban",
    cameraInfo: "Cliché d'archive Manuscrit p. 72 • Christchurch",
    excerpt: "« Visite émouvante de Christchurch, marquée par le séisme de 2011. Sa cathédrale provisoire construire en tubes de carton compressé et vitraux colorés est une œuvre d'ingéniosité magnifique. La ville renaît avec un dynamisme impressionnant. »",
    quote: "« La créativité humaine surpasse toutes les épreuves de la nature. »",
    stats: { distanceKm: 180, iconicSite: "Cardboard Cathedral Christchurch" }
  },
  {
    id: "sit-27",
    pageNum: 75,
    chapterTitle: "L'eau turquoise surnaturelle du Lac Tekapo",
    date: "3 Avril 2025",
    location: "Lake Tekapo",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Lac & Merveille",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 75 : La petite Chapelle du Bon Berger au bord du lac cyan",
    cameraInfo: "Cliché d'archive Manuscrit p. 75 • Tekapo",
    excerpt: "« On n'a jamais vu une eau d'une couleur pareille ! La farine glaciaire en suspension donne au Lac Tekapo une teinte bleu laiteuse féerique. La petite chapelle en pierre Church of the Good Shepherd offre un cadre digne d'une carte postale. »",
    quote: "« Le Lac Tekapo semble avoir été peint avec de la poudre de turquoise liquide. »",
    stats: { distanceKm: 220, iconicSite: "Church of the Good Shepherd" }
  },
  {
    id: "sit-28",
    pageNum: 78,
    chapterTitle: "Ciel étoilé exceptionnel à la réserve Mont Cook",
    date: "4 Avril 2025",
    location: "Aoraki / Mount Cook",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Étoiles & Ciel Noir",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 78 : La Voie Lactée éclatante au-dessus du Mont Cook",
    cameraInfo: "Cliché d'archive Manuscrit p. 78 • Aoraki",
    excerpt: "« Sortie nocturne à -1°C dans la réserve internationale de ciel noir. La Voie Lactée brille avec une clarté invraisemblable ! On distingue nettement la Croix du Sud. Patrice prend le temps de régler l'appareil sur trépied pour capturer ce diamant céleste. »",
    quote: "« Lever les yeux vers la Croix du Sud en pleine nuit australe : un frisson inoubliable. »",
    stats: { distanceKm: 100, iconicSite: "Aoraki Mount Cook Dark Sky Reserve" }
  },
  {
    id: "sit-29",
    pageNum: 80,
    chapterTitle: "Le glacier Franz Josef et la côte ouest sauvage",
    date: "4 Avril 2025",
    location: "Franz Josef Glacier",
    country: "Nouvelle-Zélande",
    category: "volcans",
    categoryLabel: "🌋 Glaciers & Forêt",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 80 : La langue de glace descendant jusqu'à la forêt tropicale",
    cameraInfo: "Cliché d'archive Manuscrit p. 80 • Franz Josef",
    excerpt: "« Traversée de la côte ouest battue par les vents. Le contraste entre la végétation luxuriante des fougères géantes et la langue glaciaire de Franz Josef descendante de la montagne est saisissant. »",
    quote: "« Quand la glace rencontre la jungle : la magie brute de l'Île du Sud. »",
    stats: { distanceKm: 350, iconicSite: "Franz Josef Glacier Valley" }
  },
  {
    id: "sit-30",
    pageNum: 82,
    chapterTitle: "Pancake Rocks & Souffleurs d'eau de Punakaiki",
    date: "5 Avril 2025",
    location: "Punakaiki",
    country: "Nouvelle-Zélande",
    category: "nature",
    categoryLabel: "🦘 Roches & Souffleurs",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 82 : Empilements géologiques de crêpes rocheuses",
    cameraInfo: "Cliché d'archive Manuscrit p. 82 • Punakaiki",
    excerpt: "« Les falaises ressemblent littéralement à d'immenses piles de crêpes superposées par un géant ! À marée haute, les vagues s'engouffrent dans les évents sous-marins et projettent des geysers d'écume à plus de 15 mètres de hauteur. »",
    quote: "« La sculpture géologique de la nature à Punakaiki dépasse l'imagination. »",
    stats: { distanceKm: 140, iconicSite: "Pancake Rocks Punakaiki" }
  },
  {
    id: "sit-31",
    pageNum: 84,
    chapterTitle: "Aventure en jet-boat sur la Shotover River à Queenstown",
    date: "5 Avril 2025",
    location: "Queenstown",
    country: "Nouvelle-Zélande",
    category: "rituels",
    categoryLabel: "🍷 Sensations & Vitesse",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 84 : Le Shotover Jet rasant les parois du canyon à 80 km/h",
    cameraInfo: "Cliché d'archive Manuscrit p. 84 • Queenstown",
    excerpt: "« Accrochez-vous au passe-main ! Embarquement à bord du célèbre jet-boat rouge. Le pilote frôle les parois rocheuses à quelques centimètres et réalise des 360° sur l'eau en faisant hurler tous les passagers de rire et de trouille ! »",
    quote: "« Monter à bord du Shotover Jet à 69 ans : frissons garantis ! »",
    stats: { distanceKm: 280, iconicSite: "Shotover River Canyons" }
  },
  {
    id: "sit-32",
    pageNum: 86,
    chapterTitle: "Adieux à la Nouvelle-Zélande à l'aéroport de Christchurch",
    date: "6 Avril 2025",
    location: "Aéroport de Christchurch",
    country: "Nouvelle-Zélande",
    category: "transports",
    categoryLabel: "✈️ Adieux & Émotion",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 86 : Remise des clés du 4x4 et enregistrement pour l'Australie",
    cameraInfo: "Cliché d'archive Manuscrit p. 86 • Christchurch",
    excerpt: "« On rend notre fidèle véhicule d'exploration après plus de 4500 kilomètres parcourus sur les routes sinueuses du pays du long nuage blanc. Un peu de pincement au cœur en quittant ce paradis vert, mais impatients de retrouver notre fils Jérôme à Melbourne. »",
    quote: "« Merci la Nouvelle-Zélande pour ces émotions pures. Prochaine escale : l'Australie ! »",
    stats: { distanceKm: 2400, iconicSite: "Aéroport International de Christchurch" }
  },

  // --- 5. AUSTRALIE (MELBOURNE, VICTORIA & TASMANIE) ---
  {
    id: "sit-33",
    pageNum: 87,
    chapterTitle: "Le Court-Circuit Géant d'Altona provoqué par Mam",
    date: "5 Avril 2025",
    location: "Altona (Melbourne)",
    country: "Australie",
    category: "rituels",
    categoryLabel: "🍷 Rituels & Humour",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 83 : Jérôme devant chez lui à Altona",
    cameraInfo: "Cliché d'archive Manuscrit p. 87 • Altona",
    excerpt: "« Mam ferme la lumiere avec l’interupteur de la lampe de chevet qui se trouve sur la table a coté d’elle et … BOUM …Un enorme bruit, un eclair et comme une explosion dans la chambre et Mam qui pense s’etre brulée... Je constate ensuite que c’est bien un court circuit qui a fait disjoncter le compteur de la maison. Nous sortons dans la rue et constatons que le quartier entier est privé d’electricité ! Decidement Mam est vraiment une «warrior» ! »",
    quote: "« Quand Mam touche un interrupteur en Australie, tout le quartier passe dans le noir ! »",
    stats: { distanceKm: 8200, iconicSite: "Altona Beach & Daylesford" }
  },
  {
    id: "sit-34",
    pageNum: 91,
    chapterTitle: "Retrouvailles avec Jérôme, Lola & la petite à Melbourne",
    date: "7 Avril 2025",
    location: "Melbourne",
    country: "Australie",
    category: "rencontres",
    categoryLabel: "🤝 Famille & Retrouvailles",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 91 : Repas de retrouvailles chaleureux dans la maison de Jérôme",
    cameraInfo: "Cliché d'archive Manuscrit p. 91 • Melbourne",
    excerpt: "« Quel bonheur infini d'embrasser enfin notre fils Jérôme, sa compagne Lola et notre petite-fille ! Après des mois d'éloignement à l'autre bout du globe, les câlins et les rires effacent immédiatement la fatigue du vol. On trinque autour d'un bon plat familial. »",
    quote: "« La plus belle récompense d'un voyage autour du monde est de serrer ses enfants dans ses bras. »",
    stats: { distanceKm: 20, iconicSite: "Quartier d'Altona Melbourne" }
  },
  {
    id: "sit-35",
    pageNum: 95,
    chapterTitle: "Balade sur la Great Ocean Road et les 12 Apôtres",
    date: "8 Avril 2025",
    location: "Twelve Apostles (Victoria)",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Falaises & Océan",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 95 : Les éperons calcaire spectaculaires des 12 Apôtres",
    cameraInfo: "Cliché d'archive Manuscrit p. 95 • Great Ocean Road",
    excerpt: "« Route mythique sinuant le long des falaises découpées par l'Océan Indien. Les tours de calcaire dressées dans les vagues déferlantes offrent un paysage grandiose. On s'arrête sur chaque belvédère pour immortaliser le spectacle. »",
    quote: "« La Great Ocean Road sculpte la beauté sauvage du continent australien. »",
    stats: { distanceKm: 280, iconicSite: "Twelve Apostles Port Campbell" }
  },
  {
    id: "sit-36",
    pageNum: 101,
    chapterTitle: "Lever de Soleil & Kangourous au Phare de Cape Otway",
    date: "7 Avril 2025",
    location: "Cape Otway",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Faune & Lieux Magiques",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 101 : Cape Otway natural reserve — Kangourous au petit matin",
    cameraInfo: "Cliché d'archive Manuscrit p. 101 • Cape Otway",
    excerpt: "« 5h00 le reveil sonne... Je vais admirer le lever du soleil sur le phare avec le ressas des vagues de l’ocean pacifique en musique de fond accompagné de la douceur de la pluie. Croyez moi c’est un moment hors du temps, c’est sublimissime. Puis qq mn apres le lever du soleil les kangourous sortent de partout pour se ballader autour de la maison. »",
    quote: "« Prendre son café du matin au milieu des kangourous sous le phare de l'Océan Indien. »",
    stats: { distanceKm: 220, iconicSite: "Phare historique de Cape Otway" }
  },
  {
    id: "sit-37",
    pageNum: 106,
    chapterTitle: "Vol intérieur vers Hobart, la capitale de la Tasmanie",
    date: "10 Avril 2025",
    location: "Hobart (Tasmanie)",
    country: "Australie",
    category: "transports",
    categoryLabel: "✈️ Vol & Tasmanie",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 106 : Survol de la baie d'Hobart avant l'atterrissage",
    cameraInfo: "Cliché d'archive Manuscrit p. 106 • Hobart",
    excerpt: "« Petit saut de puce au-dessus du Détroit de Bass. L'île de Tasmanie nous apparaît verdoyante et escarpée. Atterrissage sur le petit aérodrome d'Hobart sous un grand soleil printanier. Prise en main d'un nouveau véhicule pour explorer cette île légendaire. »",
    quote: "« Bienvenue en Tasmanie, l'île sauvage et préservée du bout du monde. »",
    stats: { distanceKm: 600, iconicSite: "Aéroport d'Hobart Tasmania" }
  },
  {
    id: "sit-38",
    pageNum: 112,
    chapterTitle: "À la recherche du diable de Tasmanie à Bonorong",
    date: "10 Avril 2025",
    location: "Bonorong Wildlife Sanctuary",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Faune & Diables",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 112 : Le fameux Diable de Tasmanie aux oreilles rouges",
    cameraInfo: "Cliché d'archive Manuscrit p. 112 • Bonorong",
    excerpt: "« Rencontre émouvante avec ce petit marsupial carnivore au cri féroce mais si vulnérable. Le soigneur nous explique le programme de sauvegarde de l'espèce. Mam nourrit à la main des wombats adorables et des kookaburras moqueurs. »",
    quote: "« Le Diable de Tasmanie a le cri féroce mais le cœur tendre ! »",
    stats: { distanceKm: 35, iconicSite: "Bonorong Wildlife Sanctuary" }
  },
  {
    id: "sit-39",
    pageNum: 120,
    chapterTitle: "Randonnée dans le parc de Freycinet & Wineglass Bay",
    date: "11 Avril 2025",
    location: "Freycinet National Park",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Baie Parfaite & Rando",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 120 : La courbe en forme de verre à vin de Wineglass Bay",
    cameraInfo: "Cliché d'archive Manuscrit p. 120 • Freycinet",
    excerpt: "« Ascension des blocs de granit rose des Hazards. Arrivés au col, la vue sur Wineglass Bay est époustouflante : un arc de sable blanc parfait caressé par une eau transparente. La montée fait travailler l'épaule et les cuisses, mais quel cadeau pour les yeux ! »",
    quote: "« La courbe parfaite de Wineglass Bay vaut chaque goutte de sueur versée ! »",
    stats: { distanceKm: 160, iconicSite: "Wineglass Bay Lookout" }
  },
  {
    id: "sit-40",
    pageNum: 127,
    chapterTitle: "La Dog Line et le Bagne de Port Arthur",
    date: "11 Avril 2025",
    location: "Port Arthur (Tasmanie)",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Patrimoine & Histoire",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 127 : Cellules des bagnards et tour de garde au Bagne de Port Arthur",
    cameraInfo: "Cliché d'archive Manuscrit p. 127 • Port Arthur",
    excerpt: "« À Eaglehawk Neck, ( l' isthme qui mene a port Arthur) , le chemin de mer de 30 mètres de large, qu'on appelle le cou de l'aigle faucon, est le seul passage terrestre, alors pour empêcher les évasions, les autorités ont installé une ligne de chiens agressifs... Durant 44 ans de 1833 a 1877 ce sont 12500 bagnards qui ont été envoyés a Port Arthur pour participer a la construction. »",
    quote: "« Un pan poignant d'histoire gravé dans la pierre sauvage de Tasmanie. »",
    stats: { distanceKm: 1200, iconicSite: "Bagne historique de Port Arthur" }
  },
  {
    id: "sit-41",
    pageNum: 137,
    chapterTitle: "Le Génie Excentrique du MONA à Hobart",
    date: "13 Avril 2025",
    location: "Hobart (Tasmanie)",
    country: "Australie",
    category: "rencontres",
    categoryLabel: "🤝 Culture & Lieux Insolites",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 138 : Adossé au MONA Domaine viticole de Moorilla",
    cameraInfo: "Cliché d'archive Manuscrit p. 137-138 • MONA Hobart",
    excerpt: "« David Walsh est un jeune homme issu d’une famille pauvre... Il devient un joueur invétéré qui compte les cartes a l’université de Tasmanie... Son musée sera donc souterrain, creusé dans la falaise de grés «Le contraire d’un temple qui domine et ecrase le visiteur car l’ART est en dessous». MONA devient alors une success story qui attire plus de 350000 visiteurs par an. »",
    quote: "« La création n'a aucune limite quand la passion rencontre l'excentricité. »",
    stats: { distanceKm: 50, iconicSite: "MONA Museum Hobart" }
  },
  {
    id: "sit-42",
    pageNum: 145,
    chapterTitle: "Dégustation au domaine viticole de Moorilla",
    date: "14 Avril 2025",
    location: "Moorilla Estate",
    country: "Australie",
    category: "rituels",
    categoryLabel: "🍷 Dégustation & Terroir",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 145 : Vignes en coteau surplombant la rivière Derwent",
    cameraInfo: "Cliché d'archive Manuscrit p. 145 • Moorilla",
    excerpt: "« Après la visite troublante du musée souterrain, dégustation au soleil des cuvées de Pinot Noir du vignoble de Moorilla. Un moment de grâce gourmand face au fleuve, bercé par le clapotis de l'eau. »",
    quote: "« Le bon vin rassemble les esthètes et les vagabonds de passage. »",
    stats: { distanceKm: 10, iconicSite: "Moorilla Winery Derwent River" }
  },

  // --- 6. AUSTRALIE (OUTBACK & CENTRE ROUGE) ---
  {
    id: "sit-43",
    pageNum: 152,
    chapterTitle: "Vol vers Alice Springs, la porte de l'Outback",
    date: "16 Avril 2025",
    location: "Alice Springs",
    country: "Australie",
    category: "transports",
    categoryLabel: "✈️ Désert & Poussière",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 152 : La terre rouge ocre vue du hublot de l'avion",
    cameraInfo: "Cliché d'archive Manuscrit p. 152 • Alice Springs",
    excerpt: "« Le paysage change radicalement : la terre verdoyante laisse place à une immensité ocre brûlée par le soleil. Atterrissage au cœur du Red Centre. La chaleur sèche nous enveloppe dès la descente de la passerelle. »",
    quote: "« Bienvenue dans le Centre Rouge, le cœur battant et mythique de l'Australie. »",
    stats: { distanceKm: 1800, iconicSite: "Alice Springs Airport Red Centre" }
  },
  {
    id: "sit-44",
    pageNum: 158,
    chapterTitle: "Prise en main du surpuissant Toyota Fortuner",
    date: "17 Avril 2025",
    location: "Alice Springs",
    country: "Australie",
    category: "4x4",
    categoryLabel: "🤠 4x4 & Pistes",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 158 : Le gros Toyota Fortuner blanc prêt pour les pistes",
    cameraInfo: "Cliché d'archive Manuscrit p. 158 • Alice Springs",
    excerpt: "« Prise de possession de notre monstre à quatre roues motrices : un Toyota Fortuner suréquipé. Patrice règle les rétroviseurs et vérifie la roue de secours. On charge les bidons d'eau et les provisions pour affronter la latérite. »",
    quote: "« Quand on s'enfonce dans le désert australien, le 4x4 est votre meilleure assurance-vie. »",
    stats: { distanceKm: 50, iconicSite: "Garage 4x4 Alice Springs" }
  },
  {
    id: "sit-45",
    pageNum: 163,
    chapterTitle: "Le Vol Plané du Fortuner sur la Piste Aborigène",
    date: "19 Avril 2025",
    location: "Hermannsburg Track (Outback)",
    country: "Australie",
    category: "4x4",
    categoryLabel: "🤠 Péripéties & 4x4",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 163 : Sur les pistes de la réserve aborigène",
    cameraInfo: "Cliché d'archive Manuscrit p. 163 • Hermannsburg",
    excerpt: "« lorsque nous passons un gue dans lequel je pense qu’il n’y a que peu d’eau, le trou est si profond que la voiture decolle pour retombée 3 metres plus loin en faisant a Mam la frayeur de sa vie. C’est alors qu’elle cherche a m’embrouiller en disant n’importe quoi que je lui dit « STOP LAISSE MOI CONDUIRE ». »",
    quote: "« Voler à 3 mètres du sol en 4x4 dans l'Outback : la plus grande frayeur de Mam ! »",
    stats: { distanceKm: 2800, iconicSite: "Uluru & Track d'Hermannsburg" }
  },
  {
    id: "sit-46",
    pageNum: 170,
    chapterTitle: "Coucher de soleil incandescent sur Uluru (Ayers Rock)",
    date: "20 Avril 2025",
    location: "Uluru (Ayers Rock)",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Monolithe Sacré & Soleil",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 170 : Uluru virant du rouge brique au violet incandescent",
    cameraInfo: "Cliché d'archive Manuscrit p. 170 • Uluru",
    excerpt: "« Installés avec nos chaises de camping au belvédère. À mesure que le soleil baisse sur l'horizon, le rocher sacré aborigène change de teinte minute par minute : orange, ocre, rouge sang puis violet sombre. Une émotion sacrée indicible. »",
    quote: "« Assister à la métamorphose de couleur d'Uluru est une bénédiction spirituelle. »",
    stats: { distanceKm: 450, iconicSite: "Uluru-Kata Tjuta National Park" }
  },
  {
    id: "sit-47",
    pageNum: 176,
    chapterTitle: "Marche parmi les dômes géants des Kata Tjuta",
    date: "21 Avril 2025",
    location: "Kata Tjuta (Monts Olga)",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Canyons & Dômes",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 176 : Traversée du Canyon des Vents entre les dômes ocre",
    cameraInfo: "Cliché d'archive Manuscrit p. 176 • Kata Tjuta",
    excerpt: "« Randonnée épique dans la Vallée des Vents au milieu des 36 dômes de grès rouge. Les parois abruptes s'élèvent à plus de 500 mètres. Le vent souffle en rafales rafraîchissantes dans le défilé rocheux. »",
    quote: "« Les Monts Olga sont les gardiens silencieux du désert australien. »",
    stats: { distanceKm: 50, iconicSite: "Valley of the Winds Kata Tjuta" }
  },
  {
    id: "sit-48",
    pageNum: 184,
    chapterTitle: "Contemplation du silence absolu du désert",
    date: "22 Avril 2025",
    location: "Outback Camp",
    country: "Australie",
    category: "nature",
    categoryLabel: "🦘 Silence & Désert",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 184 : Bivouac sous les étoiles dans la latérite rouge",
    cameraInfo: "Cliché d'archive Manuscrit p. 184 • Outback",
    excerpt: "« Quand le moteur du 4x4 s'arrête en plein désert, un silence irréel s'installe. Pas un bruit de voiture, pas une lumière artificielle à 200 kilomètres à la ronde. Seul le crépitement de notre feu de camp éclaire les visages. »",
    quote: "« Le vrai luxe de notre époque est le silence absolu du désert. »",
    stats: { distanceKm: 120, iconicSite: "Red Centre Desert Camp" }
  },

  // --- 7. INDONÉSIE (JAVA, BALI & SUMATRA) ---
  {
    id: "sit-49",
    pageNum: 194,
    chapterTitle: "Spiritualité à Borobudur et Sagesse de Dedi",
    date: "26 Avril 2025",
    location: "Yogyakarta",
    country: "Indonésie",
    category: "rencontres",
    categoryLabel: "🤝 Rencontres & Sérénité",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 194 : Temple de Borobudur à Java",
    cameraInfo: "Cliché d'archive Manuscrit p. 194 • Borobudur",
    excerpt: "« Ce temple Inscrit au patrimoine mondial de l’UNESCO en 1991, fut construit entre le 8eme et le 9eme siecle et est encore aujourd’hui le plus grand du monde et reste le plus visité en Asie... Dedy, ce jeune homme de 26 ans qui en fait 18 est en francais un « self made man » . Il a appris seul notre langue car c’est un amoureux de Moliere. »",
    quote: "« La vraie richesse d'un voyage réside dans l'âme de ceux qui vous guident. »",
    stats: { distanceKm: 6200, iconicSite: "Borobudur Temple Java" }
  },
  {
    id: "sit-50",
    pageNum: 199,
    chapterTitle: "Exploration des temples hindouistes de Prambanan",
    date: "27 Avril 2025",
    location: "Prambanan",
    country: "Indonésie",
    category: "rencontres",
    categoryLabel: "🤝 Temples & Sculptures",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 199 : Les flèches élancées du sanctuaire de Shiva",
    cameraInfo: "Cliché d'archive Manuscrit p. 199 • Prambanan",
    excerpt: "« Les tours aiguisées de Prambanan s'élèvent vers le ciel javanais. Dedi nous détaille les bas-reliefs relatant la légende du Ramayana. Mam admire la délicatesse des sculptures gravées dans la pierre volcanique il y a plus de mille ans. »",
    quote: "« Prambanan dresse ses flèches de pierre comme un hymne au génie humain. »",
    stats: { distanceKm: 25, iconicSite: "Prambanan Temple Complex" }
  },
  {
    id: "sit-51",
    pageNum: 208,
    chapterTitle: "Ascension Glaciale et Frayeur au Mont Bromo",
    date: "29 Avril 2025",
    location: "Mont Bromo (Java)",
    country: "Indonésie",
    category: "volcans",
    categoryLabel: "🌋 Volcans & Panoramas",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 208 : Notre carrosse à 1h du matin au Mont Bromo",
    cameraInfo: "Cliché d'archive Manuscrit p. 208-212 • Bromo",
    excerpt: "« Debout 1heure du mat comme prevu... On embarque donc avec Dedy et le chauffeur qui nous conduit vers le mont Bromo qui culmine a 2329 metres... Au sommet, la température ressentie descend à -2°C. Bref la situation n’est pas geniale lorsque soudainement Mam a le cœur qui s’emballe a plus de 150 bpm et quand elle se blotit contre moi meurtie par le froid et l’angoisse, elle semble s’étouffer alors je dois reagir vite. »",
    quote: "« Affronter un volcan en éruption à 69 ans demande de l'humilité et du courage. »",
    stats: { distanceKm: 180, iconicSite: "Caldeira du Mont Bromo" }
  },
  {
    id: "sit-52",
    pageNum: 220,
    chapterTitle: "Peno Homestay & Dégustation de Café à Sumberbuluh",
    date: "30 Avril 2025",
    location: "Gombengsari (Sumberbuluh)",
    country: "Indonésie",
    category: "rencontres",
    categoryLabel: "🤝 Rencontres & Écotourisme",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 221 : Hospitalité de Peno et de sa femme après la visite",
    cameraInfo: "Cliché d'archive Manuscrit p. 220-221 • Gombengsari",
    excerpt: "« Bref, en arriving chez Peno, Nous decouvrons une famille indonesienne qui propose , dans le petit village de « Sumberbuluh », perdu au milieu de nulle part, deux gites merveilleux... Peno connait cela , il en avait l’habitude et c’est ce pourquoi il a voulu construire ce gite un peu different et il se met à nous raconter son cursus extremement passionnant. Il est ingenieur agricole et a travaillé dans la grosse plantation de café. »",
    quote: "« L'écotourisme responsable : une rencontre authentique et humaine au cœur de Java. »",
    stats: { distanceKm: 50, iconicSite: "Peno Homestay Gombengsari" }
  },
  {
    id: "sit-53",
    pageNum: 225,
    chapterTitle: "Villa Dua Bintang & Cours de Cuisine chez Ely",
    date: "1er Mai 2025",
    location: "Munduk (Bali)",
    country: "Indonésie",
    category: "rituels",
    categoryLabel: "🍷 Gastronomie & Nature",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 225 : Hôtel avec terrasse sur la jungle à Munduk",
    cameraInfo: "Cliché d'archive Manuscrit p. 225-232 • Munduk",
    excerpt: "« L’hotel écoresponsable se trouve au beau milieu de la foret .Ttes les chambres ont une terrasse avec vue magnifique sur la splendide piscine a debordement et la jungle... Nous terminons cette journée, en decidant de faire une immersion dans la culture Balinaise à travers un cours de cuisine traditionnelle chez Rico & Ely. »",
    quote: "« Cuisiner un Nasi Goreng maison sous la jungle balinaise : pur enchantement. »",
    stats: { distanceKm: 120, iconicSite: "Villa Dua Bintang Munduk" }
  },
  {
    id: "sit-54",
    pageNum: 235,
    chapterTitle: "Sérénité au milieu des rizères en terrasses de Jatiluwih",
    date: "2 Mai 2025",
    location: "Jatiluwih (Bali)",
    country: "Indonésie",
    category: "nature",
    categoryLabel: "🦘 Rizières & Émeraude",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 235 : Les courbes émeraude du système d'irrigation Subak",
    cameraInfo: "Cliché d'archive Manuscrit p. 235 • Jatiluwih",
    excerpt: "« Des amphithéâtres de riz vert tendre s'étendent à perte de vue jusqu'au pied des montagnes. Le système d'irrigation traditionnel Subak régule l'eau depuis le IXe siècle. Une promenade au calme absolue. »",
    quote: "« Les rizières de Jatiluwih sont une sculpture vivante façonnée par des générations. »",
    stats: { distanceKm: 45, iconicSite: "Jatiluwih Rice Terraces UNESCO" }
  },
  {
    id: "sit-55",
    pageNum: 248,
    chapterTitle: "Séance Épique chez le Guérisseur à Gianyar",
    date: "4 Mai 2025",
    location: "Gianyar (Bali)",
    country: "Indonésie",
    category: "rencontres",
    categoryLabel: "🤝 Rituels & Tradition",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 249 : Demeure et cabinet de notre médecin guérisseur",
    cameraInfo: "Cliché d'archive Manuscrit p. 248-249 • Gianyar",
    excerpt: "« Nick nous conduit chez son copain le guerisseur. Sur le chemin nous decouvrons une maison magnifique... Nous avons droit a la ceremonie d’acceuil avec les offrandes puis je passe dans la salle du « billard » sur lequel je m’assied. En face de moi je peux voir des dessins de corps humains... Nick fait meme une courte video dans laquelle on me voit hurler de douleur ! »",
    quote: "« Il veut éradiquer le mal me dit-il tout en me faisant hurler de douleur ! »",
    stats: { distanceKm: 40, iconicSite: "Cabinet du Guérisseur Gianyar" }
  },
  {
    id: "sit-56",
    pageNum: 256,
    chapterTitle: "Dîner de fruits de mer sur la plage de Jimbaran",
    date: "5 Mai 2025",
    location: "Jimbaran (Bali)",
    country: "Indonésie",
    category: "rituels",
    categoryLabel: "🍷 Coucher de Soleil & Poisson",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 256 : Les tables illuminées à la bougie sur le sable",
    cameraInfo: "Cliché d'archive Manuscrit p. 256 • Jimbaran",
    excerpt: "« Les pieds nus dans le sable encore tiède. On choisit notre snapper rouge et nos langoustes fraîchement pêchées. Les grillades au feu de coque de noix de coco exhalent un parfum divin alors que le soleil sombre dans l'Océan Indien. »",
    quote: "« Un poisson grillé sur la plage de Jimbaran les pieds dans le sable : le vrai bonheur balinais. »",
    stats: { distanceKm: 30, iconicSite: "Jimbaran Bay Beach Barbecue" }
  },
  {
    id: "sit-57",
    pageNum: 265,
    chapterTitle: "Trek dans la Jungle des Orangs-Outans à Bukit Lawang",
    date: "6 Mai 2025",
    location: "Bukit Lawang (Sumatra)",
    country: "Indonésie",
    category: "nature",
    categoryLabel: "🦘 Faune & Jungle Sauvage",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 265 : Merveilleuse rencontre avec nos cousins les plus proches",
    cameraInfo: "Cliché d'archive Manuscrit p. 265 • Bukit Lawang",
    excerpt: "« Puis petit a petit ce sont plusieurs de ces grands singes qui rejoignent leur congenere lorsqu’ils s’apercoivent que nous ne representons aucun danger et nous les acompagnons longtemps dans leur lente ascension dans ces arbres jusqu’à 50 metres de hauteur. Ce que nous admirons ressemble au spectacle de danse d’une choregraphie completement irréelle. »",
    quote: "« Regarder un orang-outan dans les yeux au milieu de la canopée efface toute fatigue. »",
    stats: { distanceKm: 2200, iconicSite: "Parc National de Gunung Leuser" }
  },
  {
    id: "sit-58",
    pageNum: 268,
    chapterTitle: "Mam et son Copain Thomas le Macaque",
    date: "6 Mai 2025",
    location: "Bukit Lawang Ecolodge",
    country: "Indonésie",
    category: "nature",
    categoryLabel: "🦘 Faune & Complice",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 268 : Mam et son copain Thomas",
    cameraInfo: "Cliché d'archive Manuscrit p. 268 • Bukit Lawang",
    excerpt: "« Juste avant de franchir la porte, Mam a l’impression que qq’un a deposé qq chose devant notre porte... Son copain « macaque » veut jouer avec elle et l’attend sur la rembarde de notre chambre. Elle m’appelle pour voir la scene et lorsqu’a mon tour je sors nous entamons une improbable partie de cache cache entre les barreaux ! »",
    quote: "« Une partie de cache-cache improbable avec un macaque sur le balcon de notre écolodge. »",
    stats: { distanceKm: 0, iconicSite: "Écolodge de Bukit Lawang" }
  },

  // --- 8. JAPON (TOKYO, NIKKO, FUJI, KYOTO, HIROSHIMA, OSAKA, NARA) ---
  {
    id: "sit-59",
    pageNum: 310,
    chapterTitle: "Arrivée à Tokyo et choc culturel discipliné",
    date: "14 Mai 2025",
    location: "Tokyo (Haneda)",
    country: "Japon",
    category: "transports",
    categoryLabel: "✈️ Arrivée & Propreté",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 310 : La propreté étincelante du métro de Tokyo",
    cameraInfo: "Cliché d'archive Manuscrit p. 310 • Tokyo",
    excerpt: "« Premier contact avec l'empire du Soleil Levant. La politesse raffinée du personnel, la propreté chirurgicale des gares et le calme olympien des rameurs de métro nous laissent admiratifs. Un contraste total après l'agitation d'Asie du Sud-Est. »",
    quote: "« Le Japon vous surprend par sa discipline parfaite et sa gentillesse sincère. »",
    stats: { distanceKm: 5100, iconicSite: "Haneda Airport & Shibuya" }
  },
  {
    id: "sit-60",
    pageNum: 326,
    chapterTitle: "Festival du Sanja Matsuri & Tatouages Yakuzas à Asakusa",
    date: "16 Mai 2025",
    location: "Tokyo (Asakusa)",
    country: "Japon",
    category: "rencontres",
    categoryLabel: "🤝 Culture & Traditions",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 326 : La police ouvre les festivités de Sanja Matsuri",
    cameraInfo: "Cliché d'archive Manuscrit p. 326 • Asakusa",
    excerpt: "« Le « Sanja Matsuri » est un des principaux festivals « Shinto » à « Tokyo », il rend hommage aux trois fondateurs du « Senso-ji »... Des porteurs de palanquins de ts les quartiers, en habits de fête se mettent alors en ordre de marche... On remarque aussi quelques hommes arborant de merveilleux tatouages dans le cou et sur les bras... un jeune garcon a coté de nous, nous dit que ce sont vraissemblablement des « yakusas » ! »",
    quote: "« Être au bon endroit au bon moment : le miracle permanent du voyageur. »",
    stats: { distanceKm: 5300, iconicSite: "Temple Senso-ji Asakusa" }
  },
  {
    id: "sit-61",
    pageNum: 334,
    chapterTitle: "La Tempête Sacrée du Pont Shinkyo & Toshogu à Nikko",
    date: "17 Mai 2025",
    location: "Nikko",
    country: "Japon",
    category: "volcans",
    categoryLabel: "🌋 Lieux Sacrés & Pluie",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 336 : Visite du temple de Toshogu sous la pluie",
    cameraInfo: "Cliché d'archive Manuscrit p. 334-336 • Nikko",
    excerpt: "« En sortant du bus, nous marchons 15 mn vers le pont « Shinkyo » d’un rouge vif éclatant et dont Paula nous raconte la légende... Nous commençons par l’imposant « Toshogu », où art et histoire se mêlent au milieu de cette majestueuse foret de cèdres plusieurs fois centenaires. On y admire ses ornements et cet or qui scintille de tte part puis aussi son célèbre trio de singes sages. »",
    quote: "« La pluie du Japon ne mouille pas les vêtements, elle baptise l'esprit ! »",
    stats: { distanceKm: 160, iconicSite: "Pont Shinkyo & Toshogu" }
  },
  {
    id: "sit-62",
    pageNum: 353,
    chapterTitle: "Le Cliché Magique de la Pagode Chureito & Fujiyama",
    date: "19 Mai 2025",
    location: "Fujiyoshida (Mont Fuji)",
    country: "Japon",
    category: "volcans",
    categoryLabel: "🌋 Volcans & Panoramas",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 352 : Et voila le celebre Mont Fujiyama",
    cameraInfo: "Cliché d'archive Manuscrit p. 352-353 • Fujiyoshida",
    excerpt: "« La pagode « Chureito » qui est l’une des 1300 propriétés du sanctuaire « Arakurayama Sengen », situé à « Fujiyoshida »... Malgré le temps maussade, on eu dit que La déesse « Konohanasakuya-hime », protectrice des fleurs et des arbres du « Mont Fuji » était avec nous, car, tout d’un coup les nuages et la pluie laissent passer qq brins de lumière comme par miracle pour que je puisse faire ce pour quoi nous sommes montés. »",
    quote: "« Quand les nuages s'écartent enfin pour révéler le sommet sacré du Fujiyama. »",
    stats: { distanceKm: 110, iconicSite: "Pagode Chureito & Lac Kawaguchi" }
  },
  {
    id: "sit-63",
    pageNum: 381,
    chapterTitle: "L'Éclat du Pavillon d'Or (Kinkaku-ji) à Kyoto",
    date: "23 Mai 2025",
    location: "Kyoto",
    country: "Japon",
    category: "nature",
    categoryLabel: "🦘 Merveilles du Monde",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 380 : Le Kinkaku ou pavillon d'or",
    cameraInfo: "Cliché d'archive Manuscrit p. 380-381 • Kyoto",
    excerpt: "« C’est .un bâtiment à vraiment couper le souffle tellement il « claque aux yeux » des visiteurs avec ses 20 kilos de feuilles d’or qui couvrent la toiture. Il inspire le respect et respire la sérénité. Il porte le nom de « Kinkaku-ji » qui est le nom habituel des temples bouddhistes » Rokuon-ji » mais tout le monde s’accorde pour l’appeler « le pavillon d’or ». »",
    quote: "« S'émerveiller devant 20 kilos de feuilles d'or scintillant sur l'étang de Kyoto. »",
    stats: { distanceKm: 450, iconicSite: "Kinkaku-ji & Arashiyama" }
  },
  {
    id: "sit-64",
    pageNum: 395,
    chapterTitle: "Le Sanctuaire Céleste de Miyajima (Photo de Couverture)",
    date: "24 Mai 2025",
    location: "Miyajima (Hiroshima)",
    country: "Japon",
    category: "volcans",
    categoryLabel: "🌋 Paysages Féeriques",
    photoUrl: "preset-miyajima",
    photoCaption: "Photo du manuscrit p. 1 & 395 : Itsukushima-jinja Ō Torii (Grand tori du sanctuaire sur la mer) - Couverture officielle du livre",
    cameraInfo: "Cliché d'archive Manuscrit p. 1 & 395 • Miyajima",
    excerpt: "« C’est au travers d’une brume épaisse que nous traversons la mer intérieure de « Seto ».. « Miyajima » est le nom adopté par les japonais pour l'île d' « Itsukushima »... A mi-parcours, nous commençons a peine de distinguer le célèbre « torii » rouge qui semble comme flotter sur l’eau et nous sommes emprunts d’émotion... Ce pourrait bien être celle choisie pour le livre. »",
    quote: "« Devant la porte céleste de Miyajima, le temps s'arrête et laisse place à la paix. »",
    stats: { distanceKm: 310, iconicSite: "Sanctuaire d'Itsukushima" }
  },
  {
    id: "sit-65",
    pageNum: 420,
    chapterTitle: "Émotion au Mémorial de la Paix à Hiroshima",
    date: "25 Mai 2025",
    location: "Hiroshima",
    country: "Japon",
    category: "rencontres",
    categoryLabel: "🤝 Mémoire & Paix",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 420 : Le Dôme de Genbaku préservé comme témoignage universel",
    cameraInfo: "Cliché d'archive Manuscrit p. 420 • Hiroshima",
    excerpt: "« Recueillement silencieux devant les ruines du Dôme de la Paix. La flamme du souvenir brûle en permanence jusqu'à ce que toutes les armes nucléaires aient disparu de la Terre. Un moment de réflexion profonde sur la fragilité de notre monde. »",
    quote: "« Se souvenir du passé pour offrir un avenir de paix aux générations futures. »",
    stats: { distanceKm: 25, iconicSite: "Hiroshima Peace Memorial Park" }
  },
  {
    id: "sit-66",
    pageNum: 465,
    chapterTitle: "L'Exposition Universelle Osaka 2025 sur le Grand Ring",
    date: "31 Mai 2025",
    location: "Osaka (Yumeshima)",
    country: "Japon",
    category: "rencontres",
    categoryLabel: "🤝 Événements Mondiaux",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 467 : Présentation aléatoire de quelques pavillons autour du Ring",
    cameraInfo: "Cliché d'archive Manuscrit p. 465-467 • Osaka",
    excerpt: "« Le plus impressionnant reste cet anneau d’un diametre de presque 700 mètres et d’une circonférence de 2 km environ , aussi étrange que pénétrant qu’ils appellent le «Ring» et représente la connexion et la communion des cultures du monde entier sous les memes cieux. La construction de ce monument entièrement pensé en bois, devait être réalisée selon les methodes traditionnelles ancestrales. »",
    quote: "« Se promener à 20 mètres de hauteur sur le plus grand anneau en bois du monde. »",
    stats: { distanceKm: 50, iconicSite: "Ring de l'Expo 2025 Osaka" }
  },

  // --- 9. TAÏWAN (TAIPEI, SHIFEN & JIUFEN) ---
  {
    id: "sit-67",
    pageNum: 520,
    chapterTitle: "Escale gourmande au marché de nuit de Shilin à Taipei",
    date: "5 Juin 2025",
    location: "Taipei",
    country: "Taïwan",
    category: "rituels",
    categoryLabel: "🍷 Saveurs & Night Market",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 520 : L'effervescence colorée du marché nocturne de Shilin",
    cameraInfo: "Cliché d'archive Manuscrit p. 520 • Taipei",
    excerpt: "« Taïwan nous accueille avec une générosité culinaire incroyable ! On flâne entre les échoppes lumineuses : bao vapeur, stinky tofu cuit aux herbes et thé aux bulles artisanal. Mam déguste une brioche farcie au porc encore fumante. »",
    quote: "« Les marchés de nuit de Taïwan sont un feu d'artifice de saveurs et de convivialité. »",
    stats: { distanceKm: 1700, iconicSite: "Shilin Night Market Taipei" }
  },
  {
    id: "sit-68",
    pageNum: 532,
    chapterTitle: "L'Envol de la Lanterne à Shifen & les Ruelles de Jiufen",
    date: "6 Juin 2025",
    location: "Shifen & Jiufen",
    country: "Taïwan",
    category: "rencontres",
    categoryLabel: "🤝 Traditions & Famille",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 534 : Tradition du lancé de lanterne dans le village de Shifen",
    cameraInfo: "Cliché d'archive Manuscrit p. 532-534 • Shifen",
    excerpt: "« Nous sommes nombreux à déssiner a l’encre noire nos vœux de santé bonheur amour et prosperité sur chacunes des faces de ces lanternes... Mam porte son attention sur la famille et l’amour lorsqu’elle ecrit qq mots sur le papier rouge alors que je porte la mienne sur le bonnheur et la reussite de Kujé et Riv (business de ma fille)... Le spectacle se déroule au milieu des rails de la ligne de chemin de fer. »",
    quote: "« Envoyer nos vœux d'amour et de réussite dans le ciel de Taïwan sur une lanterne rouge. »",
    stats: { distanceKm: 2100, iconicSite: "Vieille Rue de Shifen & Jiufen" }
  },

  // --- 10. FRANCE (RETOUR & RETROUVAILLES) ---
  {
    id: "sit-69",
    pageNum: 596,
    chapterTitle: "Retour Triomphal à Rennes après 90 Jours : C'est POSSIBLE !",
    date: "14 Juin 2025",
    location: "Gare de Rennes",
    country: "France",
    category: "rencontres",
    categoryLabel: "🤝 Retrouvailles Familiales",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 596 : Retrouvailles familiales à la gare de Rennes — Un peu de nostalgie, mais heureux !",
    cameraInfo: "Cliché d'archive Manuscrit p. 596 • Rennes",
    excerpt: "« A la gare ils sont nombreux pour nous accueillir et les retrouvailles sont émouvantes puis nous rentrons tous ensemble chez Alix... Nous avons tt de meme bravé le destin pour prouver a nos enfants et petits enfants que C’EST POSSIBLE malgré les soucis que tous rencontrent un jour ou l’autre dans la vie. Il faut tjrs persévérer et aller jusqu’au bout de ses reves. »",
    quote: "« 69 ans, 69 000 km, 69 heures de vol : C'EST POSSIBLE à n'importe quel âge ! »",
    stats: { distanceKm: 9800, iconicSite: "La Gare de Rennes & Maison d'Alix" }
  },
  {
    id: "sit-70",
    pageNum: 602,
    chapterTitle: "Épilogue : Bilan et Préparation des Prochains Horizons",
    date: "20 Juin 2025",
    location: "Rennes",
    country: "France",
    category: "rencontres",
    categoryLabel: "🤝 Épilogue & Horizons",
    photoUrl: "",
    photoCaption: "Photo du manuscrit p. 602 : Tri et numérisation des notes et photos du voyage par Patrice et Mam",
    cameraInfo: "Cliché d'archive Manuscrit p. 602 • Rennes",
    excerpt: "« De retour dans la quiétude bretonne, nous étalons les cartes, les carnets de notes et les milliers de clichés pris aux quatre coins du globe. Ce livre n'est pas un point final, mais un passage de témoin : la preuve vivante qu'à 69 ans, le monde reste immense et à portée de main pour qui ose franchir le pas. »",
    quote: "« Le véritable voyage ne s'arrête pas au retour, il continue dans la mémoire et dans l'inspiration qu'il éveille. »",
    stats: { distanceKm: 0, iconicSite: "Atelier d'Écriture & Mémoire" }
  }
];
